select CONCEPT_ID, CONCEPT_NAME, COALESCE(STANDARD_CONCEPT,'N') STANDARD_CONCEPT, COALESCE(INVALID_REASON,'V') INVALID_REASON, CONCEPT_CODE, CONCEPT_CLASS_ID, DOMAIN_ID, VOCABULARY_ID
from public.concept
where (LOWER(CONCEPT_NAME) LIKE %ibuprofen% or LOWER(CONCEPT_CODE) LIKE %ibuprofen% or CAST(CONCEPT_ID as VARCHAR(255)) = ibuprofen)

order by CONCEPT_NAME ASC